# Generated by Django 3.2.3 on 2021-05-16 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('pob', models.CharField(max_length=100, null=True)),
                ('profilelink', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapyapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteAndTag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapyapp.quote')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapyapp.tag')),
            ],
        ),
    ]
