# Generated by Django 3.2.3 on 2021-05-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
