# Generated by Django 3.2.3 on 2021-05-16 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyapp', '0002_alter_quote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='createdtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='modifiedtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
